extends:
  - stylelint-config-recommended
  - stylelint-config-recommended-scss

plugins:
  - stylelint-scss

rules:
    selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - global
